
version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_api_development
      MYSQL_USER: yutaro
      MYSQL_PASSWORD: yutaro
    ports:
      - "3306:3306"
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/go/src/portfolio-api
    environment:
      PORT: 9800
      DB_HOST: db
      DB_NAME: portfolio_api_development
      DB_USER: yutaro
      DB_PASSWORD: yutaro
      PROTOCOL: tcp(db)
    ports:
      - '9800:9800'
    tty:
      true