apiVersion: v1
kind: Service
metadata:
  name: portfolio-api
  labels:
    app: portfolio-api
spec:
  type: LoadBalancer
  ports:
    - port: 9800
      targetPort: 9800
  selector:
    app: portfolio-api
